Name:           perl-Scaffold
Version:        0.11
Release:        1%{?dist}
Summary:        Scaffold Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Scaffold/
Source0:        http://www.cpan.org/modules/by-module/Scaffold/Scaffold-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Pod::Coverage)       >= 0.00
BuildRequires:  perl(Test::More)          >= 0.00
BuildRequires:  perl(Badger)              >= 0.06
BuildRequires:  perl(Plack)               >= 0.9911
BuildRequires:  perl(HTTP::Session)       >= 0.32
BuildRequires:  perl(KeyedMutex)          >= 0.06
BuildRequires:  perl(Crypt::CBC)          >= 2.17
BuildRequires:  perl(Crypt::OpenSSL::AES) >= 2.10
BuildRequires:  perl(CGI::Simple)         >= 1.112
BuildRequires:  perl(Cache::FastMmap)     >= 1.34
BuildRequires:  perl(Cache::Memcached)    >= 1.28
BuildRequires:  perl(Try::Tiny)           >= 0.04
BuildRequires:  perl(Set::Light)          >= 0.00

Requires:       perl(Module::Build)
Requires:       perl(Pod::Coverage)       >= 0.00
Requires:       perl(Test::More)          >= 0.00
Requires:       perl(Badger)              >= 0.06
Requires:       perl(Plack)               >= 0.9911
Requires:       perl(HTTP::Session)       >= 0.32
Requires:       perl(KeyedMutex)          >= 0.06
Requires:       perl(Crypt::CBC)          >= 2.17
Requires:       perl(Crypt::OpenSSL::AES) >= 2.10
Requires:       perl(CGI::Simple)         >= 1.112
Requires:       perl(Cache::FastMmap)     >= 1.34
Requires:       perl(Cache::Memcached)    >= 1.28
Requires:       perl(Try::Tiny)           >= 0.04
Requires:       perl(Set::Light)          >= 0.00
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Scaffold provides a framework to build web based applications. It tries to
make this as easy as possible with maximum flexibility. It includes the
following features:

%prep
%setup -q -n Scaffold-%{version}

%build
%{__perl} Build.PL installdirs=site
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc app Changes README
%{perl_sitelib}/*
/usr/local/share/man/man3/*

%changelog
* Fri Jan 17 2014 "build <wsysnet@wsipc.org>" 0.11-1
- Specfile autogenerated by cpanspec 1.78.
